# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "69c0449ba10710d051bd67e50dc8f23e"
name = "Vaultd"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true
