import { redirect } from "react-router";
import { unauthenticated } from "../shopify.server";
import { getAccountForShop, createAccountForShop } from "../vaultd-account.server";
import { PLAN_ORDER, PLAN_LABELS } from "../vaultd-plans";

export const loader = async ({ request }) => {
  const url = new URL(request.url);
  const plan = url.searchParams.get("plan");
  const shop = url.searchParams.get("shop");
  const host = url.searchParams.get("host") || "";

  // Build a redirect URL back into the embedded app. When `host` is present
  // App Bridge detects the non-iframe context and auto-redirects to
  // admin.shopify.com, preserving the path + params. Without `host` we
  // fall back to a direct admin.shopify.com URL.
  const shopHandle = shop?.replace(".myshopify.com", "");
  const appHandle = process.env.SHOPIFY_APP_HANDLE || "vaultd-1";

  const toPlans = (billing, planName) => {
    if (host) {
      const p = new URLSearchParams({ billing, shop: shop || "", host });
      if (planName) p.set("plan", planName);
      return `/app/plans?${p}`;
    }
    const base = `https://admin.shopify.com/store/${shopHandle}/apps/${appHandle}/app/plans`;
    return planName ? `${base}?billing=${billing}&plan=${planName}` : `${base}?billing=${billing}`;
  };

  if (!plan || !PLAN_ORDER.includes(plan) || !shop) {
    return redirect(host
      ? `/app/plans?host=${encodeURIComponent(host)}&shop=${encodeURIComponent(shop || "")}`
      : `https://admin.shopify.com/store/${shopHandle}/apps/${appHandle}/app/plans`
    );
  }

  const dbModule = await import("../db.server");
  const db = dbModule.default;

  // Get merchant email for account creation (best-effort).
  let merchantEmail = null;
  try {
    const { admin: adminAuth } = await unauthenticated.admin(shop);
    const res = await adminAuth.graphql(`{ shop { email } }`);
    const { data } = await res.json();
    if (data?.shop?.email) merchantEmail = data.shop.email.toLowerCase().trim();
  } catch {}

  // Verify the Shopify subscription is active.
  // On failure we trust the return URL (it was generated by our own
  // billing.request which requires Shopify auth).
  let verified = false;
  try {
    const { admin } = await unauthenticated.admin(shop);
    const res = await admin.graphql(`{
      currentAppInstallation {
        activeSubscriptions { name status }
      }
    }`);
    const { data } = await res.json();
    const subs = data?.currentAppInstallation?.activeSubscriptions ?? [];
    verified = subs.some(
      (s) => s.name === PLAN_LABELS[plan] && s.status === "ACTIVE"
    );
  } catch {
    verified = true;
  }

  if (verified) {
    try {
      let account = await getAccountForShop(shop);
      if (!account) {
        const result = await createAccountForShop(shop, { email: merchantEmail || undefined });
        account = result.account;
      }
      if (account) {
        await db.vaultdAccount.update({
          where: { id: account.id },
          data: { plan },
        });
      }
    } catch (_) {}
    return redirect(toPlans("confirmed", plan));
  }

  return redirect(toPlans("cancelled", null));
};
