import { redirect } from "react-router";
import { unauthenticated } from "../shopify.server";
import { getAccountForShop, createAccountForShop } from "../vaultd-account.server";
import { PLAN_ORDER, PLAN_LABELS } from "../vaultd-plans";

export const loader = async ({ request }) => {
  const url = new URL(request.url);
  const plan = url.searchParams.get("plan");
  const shop = url.searchParams.get("shop");

  const shopHandle = shop?.replace(".myshopify.com", "");

  const toAdmin = (path = "") =>
    shopHandle
      ? `https://admin.shopify.com/store/${shopHandle}/apps/${process.env.SHOPIFY_APP_HANDLE || "vaultd"}/app/${path}`
      : `/app/${path}`;

  if (!plan || !PLAN_ORDER.includes(plan) || !shop) {
    return redirect(toAdmin("plans"));
  }

  const dbModule = await import("../db.server");
  const db = dbModule.default;

  // Fetch app handle + merchant email for proper redirect URL and account sync
  let appHandle = process.env.SHOPIFY_APP_HANDLE || "vaultd-1";
  let merchantEmail = null;
  try {
    const { admin: adminAuth } = await unauthenticated.admin(shop);
    const appRes = await adminAuth.graphql(`{ app { handle } shop { email } }`);
    const { data: appData } = await appRes.json();
    if (appData?.app?.handle) appHandle = appData.app.handle;
    if (appData?.shop?.email) merchantEmail = appData.shop.email.toLowerCase().trim();
  } catch {}

  const toAdminWithHandle = (path = "") =>
    shopHandle && appHandle
      ? `https://admin.shopify.com/store/${shopHandle}/apps/${appHandle}/app/${path}`
      : `/app/${path}`;

  // Best-effort: verify the subscription is active on Shopify.
  // If the GraphQL call fails (e.g. expired offline token on dev store),
  // we still trust our own return URL and update the plan — the URL was
  // generated by billing.request which requires Shopify auth.
  let verified = false;
  try {
    const { admin } = await unauthenticated.admin(shop);
    const res = await admin.graphql(`{
      currentAppInstallation {
        activeSubscriptions { name status }
      }
    }`);
    const { data } = await res.json();
    const subs = data?.currentAppInstallation?.activeSubscriptions ?? [];
    verified = subs.some(
      (s) => s.name === PLAN_LABELS[plan] && s.status === "ACTIVE"
    );
  } catch {
    // Token expired or network error — trust the return URL (generated by us).
    verified = true;
  }

  if (verified) {
    try {
      let account = await getAccountForShop(shop);
      if (!account) {
        // If a VaultdAccount with the merchant's email exists (created on website),
        // link this shop to it instead of creating a new separate account.
        const result = await createAccountForShop(shop, { email: merchantEmail || undefined });
        account = result.account;
      }
      if (account) {
        await db.vaultdAccount.update({
          where: { id: account.id },
          data: { plan },
        });
      }
    } catch (_) {}
    return redirect(toAdminWithHandle(`plans?billing=confirmed&plan=${plan}`));
  }

  return redirect(toAdminWithHandle("plans?billing=cancelled"));
};
