import { redirect } from "react-router";
import { unauthenticated } from "../shopify.server";
import { PLAN_ORDER, PLAN_LABELS } from "../vaultd-plans";

export const loader = async ({ request }) => {
  const url = new URL(request.url);
  const plan = url.searchParams.get("plan") || "";
  const shop = url.searchParams.get("shop") || "";
  const host = url.searchParams.get("host") || "";

  const back = new URLSearchParams();
  if (host) back.set("host", host);
  if (shop) back.set("shop", shop);

  if (!plan || !PLAN_ORDER.includes(plan) || !shop) {
    back.set("billing", "error");
    return redirect(`/app/plans?${back}`);
  }

  // Update the plan in our DB, then redirect back into the app.
  // We trust the return URL (generated by our own billing.request which
  // requires Shopify auth) so a verification failure still confirms the plan.
  try {
    const { getAccountForShop, createAccountForShop } = await import("../vaultd-account.server");
    const { default: db } = await import("../db.server");

    // Verify with Shopify that the subscription is active.
    let planConfirmed = false;
    try {
      const { admin } = await unauthenticated.admin(shop);
      const res = await admin.graphql(`{
        currentAppInstallation { activeSubscriptions { name status } }
      }`);
      const { data } = await res.json();
      const subs = data?.currentAppInstallation?.activeSubscriptions ?? [];
      planConfirmed = subs.some(
        (s) => s.name === PLAN_LABELS[plan] && s.status === "ACTIVE"
      );
    } catch {
      // Token expired or network error — trust the URL.
      planConfirmed = true;
    }

    if (planConfirmed) {
      let account = await getAccountForShop(shop);
      if (!account) {
        const result = await createAccountForShop(shop);
        account = result?.account ?? null;
      }
      if (account) {
        await db.vaultdAccount.update({
          where: { id: account.id },
          data: { plan },
        });
      }
      back.set("billing", "confirmed");
      back.set("plan", plan);
    } else {
      back.set("billing", "cancelled");
    }
  } catch {
    // DB error — still redirect, congrats banner won't show.
    back.set("billing", "error");
  }

  return redirect(`/app/plans?${back}`);
};

// Required by React Router v7 file-based routing even for redirect-only routes.
export default function BillingReturn() {
  return null;
}
